import { flattenObject, kebabCase } from 'es-toolkit'

const generatedFileHeader = `/*
 * Generated by @noxflora/css. Do not edit by hand.
 */`

export function createStylesheet(contents: string): string {
    return `${generatedFileHeader}\n\n${contents}\n`
}

function normaliseSegment(segment: string): string {
    if (!/[A-Z]/.test(segment)) {
        return segment
    }

    return kebabCase(segment)
}

function buildVarName(pathSegments: string[]): string {
    return `--nox-${[...pathSegments.map(normaliseSegment)].join('-')}`
}

export function cssVar(path: string): string {
    return `var(${buildVarName(path.split('.'))})`
}

export function toCssVars(tokens: object, basePath: string[] = []): string {
    const flattenedTokens = flattenObject(tokens)
    const declarations: string[] = []

    for (const [tokenPath, value] of Object.entries(flattenedTokens)) {
        const fullPath = [...basePath, ...tokenPath.split('.')]
        const varName = buildVarName(fullPath)

        declarations.push(`${varName}: ${value};`)
    }

    return declarations.join('\n')
}
